targets:
  $default:
    builders:
      freezed:
        options:
          build_extensions:
            'lib/model/{{file}}.dart': 'lib/model/generated/{{file}}.freezed.dart'
          field_rename: snake
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/model/{{file}}.dart': 'lib/model/generated/{{file}}.g.dart'
          field_rename: snake
          ignore_for_file:
            - type=lint
            - duplicate_ignore
      json_serializable:
        generate_for:
          include:
            - "lib/**/model/*.dart"
            - "lib/**/*provider.dart"
        options:
          checked: true
          explicit_to_json: true
